--

diff --git a/tests/TEST b/tests/TEST
--- a/tests/TEST
+++ b/tests/TEST
@@ -1,6 +1,9 @@
 #!/bin/bash
 
+dir=$(pwd)
 hop=/usr/local/bin/hop
+js2esterel=/tmp/js2esterel.js
+batch=/tmp/batch.js
 CC=/usr/bin/gcc
 output_hop=/tmp/TEST-HOPJS.out
 output_est=/tmp/TEST-EST.out
@@ -17,6 +20,13 @@ run_kernel_test() {
     i=$((i + 1))
 
     echo -n "$i. $file ... "
+
+    cat <<EOF > $batch
+var batch = require("$pwd/../batch-interpreter.js");
+var example = require("$pwd/$file.js");
+batch.interperter(prg);
+EOF
+
     $hop -g --no-server $file.js < $file.in > $output_hop
     batch_esterel $file < $file.in > $output_est
 
@@ -36,6 +46,13 @@ run_js2esterel_test() {
     i=$((i + 1))
 
     echo -n "$i. $file ... "
+
+    cat <<EOF > $js2esterel
+var js2esterel = require("$pwd/../js2esterel.js");
+var example = require("$pwd/$file.js");
+console.log(example.prg.esterel_code());
+EOF
+
     $hop -g --no-server $file.js < ${file%-js2esterel}.in > $output_hop
 
     if [ "$(diff -Z $output_hop $file.out)" != "" ]
@@ -65,6 +82,12 @@ print_stats() {
 if [ -z $ESTEREL ]
 then
     echo "ERROR: Esterel needs to be installed."
+    exit 1
+fi
+
+if [ "$(dirname $0)" != "." ]
+then
+    echo "ERROR: The tests must be run inside test directory"
     exit 1
 fi
 
